FROM golang:latest

# Install dep
RUN go get -u github.com/golang/dep/cmd/dep

WORKDIR /go/src
COPY . github.com/webflow/oauth2_proxy
WORKDIR /go/src/github.com/webflow/oauth2_proxy

# Load pinned dependencies into vendor/
RUN dep ensure -v

# Build and strip our binary
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w -X main.Version=`git log --pretty=format:'%h' -n 1`" -a -installsuffix cgo -o oauth2_proxy .