FROM ubuntu

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get -y dist-upgrade

# Copy the binary over from the builder image
COPY oauth2_proxy /

COPY entrypoint.sh /
RUN chmod 755 /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

CMD ["oauth2_proxy", "--config", "/conf/oauth2_proxy.cfg"]
