FROM ubuntu

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get -y dist-upgrade

# Copy the binary over from the builder image
COPY oauth2_proxy /

# Run our entrypoint script when the container is executed
CMD ["/oauth2_proxy"]
